Repository FelixVanOost/Strava-Analysis-Tool, pull requests merged in 2020-05, with the labels that each got.

#63 Replace formatted date string with ISO 8601 object when generating geo data file
  analysis.py
  geo.py
  here_xyz.py
Labels: enhancement

#64 Define consistent colour palette across plots
  analysis.py
Labels: enhancement

#66 Add configuration file
  README.md
  analysis.py
  config.toml
  environment.yml
  requirements.txt
  strava_analysis_tool.py
  strava_auth.py
  strava_data.py
Labels: enhancement

#69 Use stricter isoparser to parse strings into DateTime objects
  strava_data.py
Labels: bug

#72 Add messaging for non-api rate limit errors
  strava_data.py
Labels: enhancement

#74 Update Python 3.8 dependencies
  environment.yml
  requirements.txt
Labels: dependencies

#76 Remove use of shell in subprocess
  here_xyz.py
Labels: enhancement
